### ISSUE TITLE
Feature request - M5Stick C - Microphone.

### ISSUE THREAD

**Issue by Ajb2k3** [m5stack/UiFlow-Bug-Report#10]
Value block - returns an analogue value from the mic.
Mic Write - Directly writes detected audio data to the Sdcard as a wave file.

**Comment by Zontex** [comment]
Hello,
We've created a new topic called "wish list" in forum.m5stack.com please feel free to fill your wish over there and we will push it forward as this repository is mainly for bug reports and wishes or feature requests might be difficult to get attention over here, thanks!
