### ISSUE TITLE
[Feature Request] RS485

### ISSUE THREAD

**Issue by Ajb2k3** [m5stack/UiFlow-Bug-Report#11]
6060 Push - Push (distance) - Pull (distance)
AC socket - Socket (On/Off)

General - 
RS485 Read() - Reads the RS485 Bus.
RS485 Write() - Writes to the RS485 Bus.
Broadcast Read() - Scan the RS485 Bus for devices and addresses and returns them in a similar fashion to the I2C functions.

**Comment by EeeeBin** [comment]
6060 and acsocket will support those days, but rs485 can use instead

**Comment by Ajb2k3** [comment]
I'm really struggling to work out how to use RS485

**Comment by dburnier** [comment]
More than 1 year has passed : Please open the source code of your UiFlow Desktop IDE like that many people can help you by contributing on many aspects that your nice tool should profite !

**Comment by Zontex** [comment]
Hello,
We've created a new topic called "wish list" in forum.m5stack.com please feel free to fill your wish over there and we will push it forward as this repository is mainly for bug reports and wishes or feature requests might be difficult to get attention over here, thanks!
