### ISSUE TITLE
v1.4.0 / UI / Image / Set is not refreshed

### ISSUE THREAD

**Issue by MateuszZiolek** [m5stack/UiFlow-Bug-Report#12]
Hi,
full desc is here: http://community.m5stack.com/topic/1367/uiflow-1-4-0-ui-image-set-is-not-refreshed
Looks like Uploaded images to core is not refreshing in case of select / UI / Image / set image to
![1570282488046-3ddc5b85-0d97-4e9a-be9b-3af07eb15d5b-image](https://user-images.githubusercontent.com/46287652/66392725-fab2c500-e9d0-11e9-8fc6-dfc73d27e8df.png)
![1570282565851-c8b76a7e-d874-4e09-bf71-07ca2bbb9369-image](https://user-images.githubusercontent.com/46287652/66392736-030b0000-e9d1-11e9-8388-d3ff0842c295.png)

**Comment by EeeeBin** [comment]
fixed

**Comment by MateuszZiolek** [comment]
When its will be alive ? Still in 1.4.1 the bug exist.
