### ISSUE TITLE
[Feature request ] ESP-MESH

### ISSUE THREAD

**Issue by IoTNoob** [m5stack/UiFlow-Bug-Report#13]
Please take a look on **ESP-MESH**
https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/mesh.html
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/network/esp_mesh.html
https://github.com/espressif/esp-mdf

Since we have now ESPNOW lets do next step and grab ESP-MESH as well.

Regards
Mateusz

**Comment by EeeeBin** [comment]
This is a future demand, but recently there may not be time to do this. Sorry ....

**Comment by MateuszZiolek** [comment]
Yes its long run request. Lets keep it open ok ?

**Comment by dburnier** [comment]
Please open the source code of your UiFlow Desktop IDE like that many people can help you y contributing on many aspect that your nice tool should profite !

**Comment by Zontex** [comment]
Hello,
We've created a new topic called "wish list" in forum.m5stack.com please feel free to fill your wish over there and we will push it forward as this repository is mainly for bug reports and wishes or feature requests might be difficult to get attention over here, thanks!
