### ISSUE TITLE
[Feature Request] Image transparency

### ISSUE THREAD

**Issue by peterbay** [m5stack/UiFlow-Bug-Report#14]
Can you please add option for setting transparency color for images? It's possible to set transparency in default API, but not in uiflow.
https://docs.m5stack.com/#/en/api/lcd?id=drawbitmap
Thanks Petr V.

**Comment by EeeeBin** [comment]
Currently uiflow does not implement this function. uiflow api in here
https://github.com/m5stack/UIFlow-Code/wiki/Display#tftimagex-y-file-scale-type
