### ISSUE TITLE
[Feature request ] Multiple Flow host's

### ISSUE THREAD

**Issue by MateuszZiolek** [m5stack/UiFlow-Bug-Report#15]
Hi,
Flow usage is rising, and i would like to suggest to make more then one flow instance.
Its should be 3 Main instances US / Europe and China to balance the requests.

> C:\Users\x>ping flow.m5stack.com
> Pinging flow.m5stack.com [112.74.83.120] with 32 bytes of data:
> Reply from 112.74.83.120: bytes=32 time=235ms TTL=46
> Reply from 112.74.83.120: bytes=32 time=231ms TTL=46
> Reply from 112.74.83.120: bytes=32 time=233ms TTL=46
> Reply from 112.74.83.120: bytes=32 time=234ms TTL=46
> 
> Ping statistics for 112.74.83.120:
>     Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
> Approximate round trip times in milli-seconds:
>     Minimum = 231ms, Maximum = 235ms, Average = 233ms

Its was at mid of day in Europe and night time in Hangzhou.

Since 2 weeks period i am testing simple remote connections via Flow and its quite often there is no connection via GUI and i have to reconnect core and try it again.

Ultimate solution could be releasing the code of Flow server and then ppl could make own servers to host own requests.

Regards
Mateusz

**Comment by EeeeBin** [comment]
Sorry, for some reason, the server has been migrated and is currently looking for a suitable solution

**Comment by EeeeBin** [comment]
we add other server, http://flow01.m5stack.com and firmware is 1.4.1-beta.sg
