### ISSUE TITLE
Not possible to copy/ paste code in Mac version of offline ide

### ISSUE THREAD

**Issue by lukasmaximus89** [m5stack/UiFlow-Bug-Report#16]
Copying and pasting is impossible in the Mac version of the UIflow offline ide
no matter whether its 1.2.3 version or 1.4.2

**Comment by nikulesko** [comment]
I have the same problem for version 1.4.5 in macOS Catalina.

**Comment by lukasmaximus89** [comment]
I've mentioned this many times but it doesn't seem that the developers think its a big issue. I recommend you to use vscode or mu for micropython coding

**Comment by nikulesko** [comment]
@lukasmaximus89 I see, ok, thank you

**Comment by danielrosero** [comment]
This is ridiculous.
