### ISSUE TITLE
Missing Beta Icon in 1.2.3 option of Uiflow Mac IDE version 1.4

### ISSUE THREAD

**Issue by lukasmaximus89** [m5stack/UiFlow-Bug-Report#17]
![Screen Shot 2019-10-08 at 15 19 45](https://user-images.githubusercontent.com/24423531/66404004-859abc00-e9df-11e9-9207-3b6b1d7fed9c.png)

**Comment by EeeeBin** [comment]
Try refresh web page, it maybe appear
