### ISSUE TITLE
Extra \ generated in python code when new line "\n" is added to lcd.print or label block

### ISSUE THREAD

**Issue by lukasmaximus89** [m5stack/UiFlow-Bug-Report#18]
![Screen Shot 2019-10-08 at 15 29 55](https://user-images.githubusercontent.com/24423531/66404541-926bdf80-e9e0-11e9-9c24-e00fbfd357a1.png)
![Screen Shot 2019-10-08 at 15 30 06](https://user-images.githubusercontent.com/24423531/66404544-9435a300-e9e0-11e9-9c24-484144c4134c.png)

**Comment by Zontex** [comment]
Hello, seems we fixed this issue, please confirm and if you have any other troubles, feel free to re-open this issue.
