### ISSUE TITLE
Function to save Python code.

### ISSUE THREAD

**Issue by mongonta0716** [m5stack/UiFlow-Bug-Report#2]
Use Version 1.4.0 Beta Online

I do rough coding with blocks using UIFlow, and then fine processing is realized with Python code.

However, I'm very inconvenient because I don't have the ability to save Python code. Can you add the ability to save and open Python code?

**Comment by EeeeBin** [comment]
you can use ctrl+a select all code, and ctrl+c copy to your local py file

**Comment by mongonta0716** [comment]
I have already made use of that method. Don't you think it's strange that you can't save directly from UIFlow?

**Comment by EeeeBin** [comment]
Save button already exists，If add new one, it will be confusing

**Comment by mongonta0716** [comment]
It would be more confusing for users to lose their customized source.

Is it possible to create a function that can return customized sources to customized blocks?

**Comment by Ajb2k3** [comment]
May be add a function to the save switch so that in Micropython mode, hitting the save button will create a .py file instead of the .m5f file.

**Comment by BlackBuffaloBibi** [comment]
...'''Peut être ajouter une fonction au commutateur d'enregistrement de sorte qu'en mode Micropython, le fait de cliquer sur le bouton Enregistrer crée un fichier .py au lieu du fichier .m5f.''''.... c'est necessaire de pouvoir enregistrer des sources .py directement dans UiFlow..

**Comment by Zontex** [comment]
Hello, seems the issue got solved in the new version of UIFlow, please check and if not feel free to open it again.
