### ISSUE TITLE
[Feature request ] StickC / Stick - build in IR missing 

### ISSUE THREAD

**Issue by IoTNoob** [m5stack/UiFlow-Bug-Report#25]
Hi,
inside StickC and Stick Gray we have IR led with is still not supported in the UiFlow.
In 1.4.1b for StickC
and also in 1.2.3 for Gray there is no IR under Hardware.

Regards
Mateusz

**Comment by Zontex** [comment]
Hello,
We've created a new topic called "wish list" in forum.m5stack.com please feel free to fill your wish over there and we will push it forward as this repository is mainly for bug reports and wishes or feature requests might be difficult to get attention over here, thanks!
