### ISSUE TITLE
Stick Gray is not any more supported since UiFlow 1.2.3

### ISSUE THREAD

**Issue by MateuszZiolek** [m5stack/UiFlow-Bug-Report#26]
Hi,
what is a reason of no support for Stick Gray with is still on sale in UiFlow ?
Last supported version is 1.2.3 with is to old ... and we are missing so many good blocks.

There was some talk about end of live but rly ? we can still buy it via shop ...

Regards
Mateusz

**Comment by EeeeBin** [comment]
UIFlow not support stick gray now....
you can try use arduino to develop
