### ISSUE TITLE
1.4.1 (StickC) - Unit Neopixel isnt defined.

### ISSUE THREAD

**Issue by Ajb2k3** [m5stack/UiFlow-Bug-Report#28]

**Comment by EeeeBin** [comment]
![image](https://user-images.githubusercontent.com/24584225/67645637-d5c4c880-f964-11e9-88ad-e956432d1866.png)
Fine

**Comment by Ajb2k3** [comment]
When run on stick screen says neopixel0 not defined.

**Comment by EeeeBin** [comment]
Test run well, please refresh web page
