### ISSUE TITLE
SD-Updater support 

### ISSUE THREAD

**Issue by mongonta0716** [m5stack/UiFlow-Bug-Report#3]
Is it difficult to release UIFlow firmware that supports SD-Updater as a bin file?
The next version of SD-Updater will be able to use up to "minimal SPIFFS (Large App with OTA)".

[M5Stack-SD-Updater](https://github.com/tobozo/M5Stack-SD-Updater/)

Version 1.4.0 Beta Online

**Comment by mongonta0716** [comment]
If it is impossible, you can reply that this issue is not possible.

If impossible:
When I rewrite the firmware for UIFlow and ArduinoAPP many times, there are many steps to change the WiFi access point. Can you support SmartConfig?

https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/network/esp_smartconfig.html

**Comment by EeeeBin** [comment]
This issue is not possible, and micropython not support smartconfig yet

**Comment by mongonta0716** [comment]
I See.
