### ISSUE TITLE
Feature Request: bluetooth in micropython

### ISSUE THREAD

**Issue by ckuethe** [m5stack/UiFlow-Bug-Report#31]
Hi Folks,

The upstream version of MicroPython supports [bluetooth](https://docs.micropython.org/en/latest/library/ubluetooth.html) on the ESP32. Can I request that [M5Stack MicroPython](https://github.com/m5stack/M5Stack_MicroPython) be updated to support bluetooth. 

Thanks!

**Comment by Zontex** [comment]
Hello,
We've created a new topic called "wish list" in forum.m5stack.com please feel free to fill your wish over there and we will push it forward as this repository is mainly for bug reports and wishes or feature requests might be difficult to get attention over here, thanks!
