### ISSUE TITLE
UiFlow has long load time :-/

### ISSUE THREAD

**Issue by JosefJezek** [m5stack/UiFlow-Bug-Report#32]
Could you improve load time in Europe?

http://flow.m5stack.com

![image](https://user-images.githubusercontent.com/2110319/69287436-89347c00-0bf6-11ea-86e1-77f0239a9a75.png)

**Comment by Gitshaoxiang** [comment]
in the foreign , you can use flow01.m5stack.com , it will be quickly ,  also your device need to burn the UIFlow.sg version firmware , then it can working normal

![image](https://user-images.githubusercontent.com/45260108/69390265-9d1cd280-0d09-11ea-8716-798384593f81.png)

**Comment by JosefJezek** [comment]
![image](https://user-images.githubusercontent.com/2110319/69465028-4ef6e600-0d80-11ea-909c-0a75f4472b99.png)

**Comment by Gitshaoxiang** [comment]
It looks faster .

**Comment by Zontex** [comment]
Hello, we fixed this issue, seems it was server related but now everything should work fine.
