### ISSUE TITLE
Please enable the StickC Neoflash in UIFlow!

### ISSUE THREAD

**Issue by Ajb2k3** [m5stack/UiFlow-Bug-Report#35]
Please enable the StickC Neoflash in UIFlow!
I need the neoflash usable for holiday!

**Comment by Zontex** [comment]
Hello,
We've created a new topic called "wish list" in forum.m5stack.com please feel free to fill your wish over there and we will push it forward as this repository is mainly for bug reports and wishes or feature requests might be difficult to get attention over here, thanks!
