### ISSUE TITLE
HIDE UI Button Blocks Hat and Units Choice Button

### ISSUE THREAD

**Issue by rupin** [m5stack/UiFlow-Bug-Report#36]
Please see image below, the HIDE UI button (bottom left corner) hides the Hat and Unit choices on Firefox Browser.

![image](https://user-images.githubusercontent.com/460081/69694627-71319080-10ff-11ea-8600-06e69ebdc4b6.png)

Also, sometimes, the Hide UI button works funny and the Hat and Unit choices disappears.

![image](https://user-images.githubusercontent.com/460081/69695714-56f9b180-1103-11ea-9d06-0470a3748803.png)

**Comment by EeeeBin** [comment]
This is caused by the low screen resolution. Sorry we cannot adapt to the low resolution screen at the moment.

**Comment by rupin** [comment]
Why cant we shift the button up or change it to something smaller or
thinner?

I am fairly certain there are people like me who still use older laptops.

BTW, the issue can be circumvented by shifting the browser in fullscreen
mode.

Is there a github repository which users can download and deploy their own
instance of uiflow?

**Comment by EeeeBin** [comment]
deploy is being realized, the update time is maybe January

**Comment by Zontex** [comment]
Hello, we seem to deployed an update that fixed this issue, please check it. if you are still having troubles, feel free to re-open the issue and I will take a look into it.
