### ISSUE TITLE
[Feature request]v1.4.4 / Blocks for countermeasures against "Network is disconnected".

### ISSUE THREAD

**Issue by mongonta0716** [m5stack/UiFlow-Bug-Report#42]
When running UIFlow programs from a browser

Reproduction steps
・ Execute the program with M5Stack
・ Rewrite the program and execute again
・ The network is disconnected and an error occurs.

Resetting the M5Stack allows the rewritten program to be executed.

With M5StickC, the problem does not occur and a new program is executed.

**Comment by mongonta0716** [comment]
When I checked it later, it was due to "wifi connect".(The same phenomenon occurred with M5StickC.)

![UIFlowIssue02](https://user-images.githubusercontent.com/24690724/75090193-d6ccd600-55a3-11ea-8adf-4f983743f04e.PNG)

If there is a block that knows whether or not it is connected to UIFlow, this problem can be avoided.

**Comment by EeeeBin** [comment]
Sorry, 
Do you mean: if double click `run`, network will disconnected

**Comment by mongonta0716** [comment]
No.
If I use wificonnect, the program will not be rewritten even if I press the "execute button".
This is the second run, not a double click.

**Comment by mongonta0716** [comment]
This issue can be avoided by having "UIFlow is connected"

**Comment by Zontex** [comment]
Hello,
We've created a new topic called "wish list" in forum.m5stack.com please feel free to fill your wish over there and we will push it forward as this repository is mainly for bug reports and wishes or feature requests might be difficult to get attention over here, thanks!
