### ISSUE TITLE
[Feature request ]ESP NOW Block

### ISSUE THREAD

**Issue by mongonta0716** [m5stack/UiFlow-Bug-Report#43]
I wanted to switch the connection destination of ESPNOW, but with the current specifications, there are many steps, so I request a change of the ESPNOW block of UIFlow.

Macaddress: String variable
Id: Number

![UIFlow20200222](https://user-images.githubusercontent.com/24690724/75089087-8f8d1800-5598-11ea-9c05-5a142ced2945.PNG)

**Comment by Zontex** [comment]
Hello,
We've created a new topic called "wish list" in forum.m5stack.com please feel free to fill your wish over there and we will push it forward as this repository is mainly for bug reports and wishes or feature requests might be difficult to get attention over here, thanks!
