### ISSUE TITLE
[Feature request] StickC Microphone documentation or example

### ISSUE THREAD

**Issue by danjferg** [m5stack/UiFlow-Bug-Report#44]
Please provide functionality, documentation, and/or example on accessing microphone data from UIFlow on the M5StickC.

**Comment by Zontex** [comment]
Hello,
We've created a new topic called "wish list" in forum.m5stack.com please feel free to fill your wish over there and we will push it forward as this repository is mainly for bug reports and wishes or feature requests might be difficult to get attention over here, thanks!
