### ISSUE TITLE
[Feature request ] Wifi Hostname

### ISSUE THREAD

**Issue by IoTNoob** [m5stack/UiFlow-Bug-Report#48]
Hi,
by default when we are connecting to AP the hostname is **espressif**
if we have more then one devices it could be a bit of mess in Dhcp list.

There is a way to spec a Hostname in MP: **config(dhcp_hostname='Hostname')**
```
def do_connect():
    import network
    wlan = network.WLAN(network.STA_IF)
    wlan.active(True)
    if not wlan.isconnected():
        print('connecting to network...')
	wlan.config(dhcp_hostname='Hostname')
        wlan.connect('SSID', 'Pass')
        while not wlan.isconnected():
            pass
    print('network config:', wlan.ifconfig())
```
here is example 3 units and one got custom hostname.
![image](https://user-images.githubusercontent.com/46287652/81220229-423e1580-8fe1-11ea-96e9-9e9b64a966cd.png)

Would be great if Hostname could be added for example from M5Burner level like now we have SSID and Password.

Regards

**Comment by EeeeBin** [comment]
Hi IoTNoob,
Maybe use **ESP32-apikey** (ESP32-AB123455) or **esp-apikey[2:8]** (ESP-123456) will easy to find device 
Burner add hostname  is not easy -_-
