### ISSUE TITLE
SDCard Block wish list

### ISSUE THREAD

**Issue by Ajb2k3** [m5stack/UiFlow-Bug-Report#5]
Can we get the following blocks?

SDMount() - Function - Mounts card
SDUnmount() - function - Unmount card
SDRead() - function - reads a user specified filename
SDListDir() - Function - Returns a list of files in a user specified location
SDWrite() - function - writes to a user specified filename
SDOpenFile() - function - Opens a user specified file but must be run before SDRead and SDWrite functions
SDCloseFile() - function  - Must be called after SDRead and SDWrite functions to save data.

**Comment by EeeeBin** [comment]
sd card block will update in this week

**Comment by EeeeBin** [comment]
fixed
