### ISSUE TITLE
[M5Burner](and beta) I would like to be able to enter my SSID and password.

### ISSUE THREAD

**Issue by mongonta0716** [m5stack/UiFlow-Bug-Report#50]
I can't use it even though it came to be able to set WiFi from M5Burner with M5Atom support.
I would like this feature to be carried over.

![UIFlowbug2](https://user-images.githubusercontent.com/24690724/82069108-d6a92600-970d-11ea-9c0b-4b3c2552da49.PNG)
![UIFlowbug1](https://user-images.githubusercontent.com/24690724/82069113-d741bc80-970d-11ea-8c75-32e75b9ec35b.PNG)

**Comment by EeeeBin** [comment]
Sorry, this burner version can`t adjust fire set ssid
This will restore in next burner version

**Comment by EeeeBin** [comment]
Burner2 fixed it
