### ISSUE TITLE
Support loading images from RAMfs

### ISSUE THREAD

**Issue by remixer-dec** [m5stack/UiFlow-Bug-Report#56]
Since flash memory has limited amount of write cycles, it would be nice to have an option to store images obtained from the Internet / UART in RAM , which is currently possible [(Demo code)](https://maixpy.sipeed.com/en/libs/standard/uos.html#ioctlop-arg). I'm able to use this fs to read/write data, execute scripts from it, however, attempt to display images from RAMfs causes kernel panic. 
```
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400fca87  PS      : 0x00060330  A0      : 0x800fd3b4  A1      : 0x3ffc20c0  
A2      : 0x3ffcf6bc  A3      : 0x00000000  A4      : 0x3ffc21b8  A5      : 0x78000000  
A6      : 0x0000000b  A7      : 0x00000000  A8      : 0x3ffc21a0  A9      : 0x3f4005b0  
A10     : 0x00000000  A11     : 0x00000000  A12     : 0x80093540  A13     : 0x3ffc2030  
A14     : 0x00000003  A15     : 0x00060023  SAR     : 0x00000001  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000020  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0x00000000  

ELF file SHA256: 0000000000000000000000000000000000000000000000000000000000000000

Backtrace: 0x400fca87:0x3ffc20c0 0x400fd3b1:0x3ffc2140 0x400fdc28:0x3ffc21a0 0x401074bd:0x3ffc21f0 0x4010e4b5:0x3ffc2440 0x400e3215:0x3ffc25b0 0x400df209:0x3ffc25e0 0x400df30d:0x3ffc2600 0x400ec981:0x3ffc2620 0x400e32dc:0x3ffc26c0 0x400df209:0x3ffc2740 0x400df232:0x3ffc2760 0x4011572f:0x3ffc2780 0x40115821:0x3ffc2810 0x400f42da:0x3ffc2840 0x40093352:0x3ffc2870
```

Both m5stack.lcd.image and m5ui.M5Img crash.  
Image used for testing: default.jpg copied from the flash
Device: m5StickC  
Firmware: UIFlow 1.6.2 
  
P.S. Do you have any plans to add PNG support?

**Comment by EeeeBin** [comment]
Hi, remixer-dec
Don't worry about the life of flash memory, it can erase and write more than 100,000 times
And uiflow not support load img from ram..
And PNG, emmm, we will try it in these days

**Comment by remixer-dec** [comment]
~100 000 seems good enough for reflashing, but for projects with frequently updated images it seems a bit risky. I saw [someone](https://forum.m5stack.com/topic/2145/m5stickc-cannot-write-bmp-jpg-raw-to-the-lcd-from-memory/2) on the forum also trying to find a solution. If it's not easy to fix, ok then, you can close this issue.
Good news, thank you for the reply.

**Comment by remixer-dec** [comment]
Hi again. I [made](https://github.com/remixer-dec/mpy-img-decoder) a custom PNG decoder and ported a JPEG decoder to micropython, and used it in [my project](https://github.com/remixer-dec/M5Stack_Experiments/tree/master/M5StickC/UIFlow/TwitchClient). Even though, it was quite challenging, and the result performs slower than C module and has more memory limitations, I guess it's a solution for this issue.
