### ISSUE TITLE
[Feature request] Core 2 - Compatibility with rshell/pymakr and stubbers

### ISSUE THREAD

**Issue by persello** [m5stack/UiFlow-Bug-Report#57]
Hello, I recently bought a Core 2 and I tried UIFlow on it. I think it's a great device with lots and lots of flexibility. It would be awesome to use it like a "standard" Micropython board.

When I say standard I mean something that is compatible with other tools and VS Code extensions. For example, I'd like to use the micropy-cli stubber for generating autocomplete suggestions for Intellisense.

There are also some extensions on VS Code that allow to sync your work folder with the Micropython board, so you can have your files on your PC and add them to a git repository. One of these extensions (which is my favourite) is Pymakr, but unfortunately the board doesn't get recognized and it hangs during the connection, without showing errors.

I think this should be feasible because I built a base MicroPython firmware for my Core 2 and I was able to get this extension to work, but with no display/touchscreen/PMIC drivers, the board is almost useless.

Ideally, I would like to use a "bare" firmware with only the base drivers and libraries (such as lvgl) for working with the new Core 2, but I think this would be a lot different from the firmware that we have now.

Could it be possible to have a "basic" MicroPython firmware with your drivers or at least some compatibility between UIFlow and some external tools?

**Comment by imliubo** [comment]
Hi @persello ,
In fact, I'm doing this work, but the efficiency may be a bit slow, because there are still major tasks to do. At present, I only wrote a little power management driver, and the most basic drivers such as screen and touch are not supported yet. , But it will be as soon as possible.
Maybe you can doing this with me :)

M5Stack micropython repo: [It's only support Core2 for now](https://github.com/imliubo/M5Stack-micropython)

**Comment by persello** [comment]
@imliubo Thank you, this is what I was searching for. In the next days I'll check it out. I have some experience with lvgl in C and I already used a larger ILI display, but I'm quite a beginner with Micropython. I flashed my board today but still didn't try the AXP driver. My major issue were the datasheets written only in Chinese, I tried reading some code from various libraries but it didn't end up well, since the majority of them target another variant of the AXP chip.

Anyways, I'll leave this issue open in regard to the rshell/REPL part, but I'll mostly follow your work since I'm really interested in it and I'd like to (at least try) to help.

**Comment by Zontex** [comment]
Hello,
We've created a new topic called "wish list" in forum.m5stack.com please feel free to fill your wish over there and we will push it forward as this repository is mainly for bug reports and wishes or feature requests might be difficult to get attention over here, thanks!
