### ISSUE TITLE
Using networking in a UiFlow program breaks screen management

### ISSUE THREAD

**Issue by dlparker** [m5stack/UiFlow-Bug-Report#6]
Using the standalone UiFlow tool, it should be possible to build programs that connect the wifi and do things (such as mqtt ops). However, if you use any UI elements and then do the wifi connect process, then the UI elements are broken. They disappear and may or may not come back if later code updates the element (such as a label). This is because the wifiCfg do_connect call clears the screen and writes directly to the screen using lcd commands. 

One workaround that would be valuable for other reasons is to let the UiFlow UI elements startup be delayed until the program wants them. That would make it possible to do direct lcd calls before starting the UiFlow elements, which might sometimes be useful. To solve this problem the program could wait until the wifi connect succeeds before starting the UI.

This bug was detected using UiFlow studio 1.3.2 and m5stack version 1.4.0

**Comment by EeeeBin** [comment]
Will fixed next version

**Comment by EeeeBin** [comment]
fixed
