### ISSUE TITLE
V1.7.8 Custom blocks are no longer reflected.

### ISSUE THREAD

**Issue by mongonta0716** [m5stack/UiFlow-Bug-Report#68]
I was able to use custom blocks until 1.7.7, but after 1.7.8, custom blocks are no longer displayed after loading m5b files. Is there any change?

I'm using 1.7.7-fire as it seems to be the latest version for the terminal.

**Comment by imliubo** [comment]
Hi @mongonta0716 ,
Thank you for the report. We are investigating this issue and will notify you as soon as there is progress.

**Comment by imliubo** [comment]
Hi @mongonta0716 ,
The bug has been fixed.Thanks for reported.
Please feel free to reopen if the issue is not resolved to your satisfaction.

**Comment by mongonta0716** [comment]
Thanks!
