### ISSUE TITLE
[Feature request] StickC IR On and IR OFF blocks

### ISSUE THREAD

**Issue by Ajb2k3** [m5stack/UiFlow-Bug-Report#7]
At present there are no blocks for using the IR LED on the stick C.
As a minimum can we get an IR On block and an IR Off block?

**Comment by EeeeBin** [comment]
Sure, I am also considering how the IR function needs support.

**Comment by dburnier** [comment]
More than 1 year has passed : Please open the source code of your UiFlow Desktop IDE like that many people can help you by contributing on many aspects that your nice tool should profite !

**Comment by Zontex** [comment]
Hello,
We've created a new topic called "wish list" in forum.m5stack.com please feel free to fill your wish over there and we will push it forward as this repository is mainly for bug reports and wishes or feature requests might be difficult to get attention over here, thanks!
