### ISSUE TITLE
Title Show/Hide Block Should be made same as others.

### ISSUE THREAD

**Issue by Ajb2k3** [m5stack/UiFlow-Bug-Report#8]
Currently Title has separate Show and and blocks but identical python code as Label, Rectangle and circle.
Please merge the Title Show and Hide blocks into one to match the Label, Circle and rectangle Show/Hide blocks.

**Comment by Zontex** [comment]
Hello, it seems we fixed it in the new version of UIFlow, could you please confirm? if not, let me know and feel free to re-open it so I could take care of this.
