### ISSUE TITLE
HTTP Block Generating Incorrect Code

### ISSUE THREAD

**Issue by rupin** [m5stack/UiFlow-Bug-Report#9]
According to 
https://techtutorialsx.com/2017/06/11/esp32-esp8266-micropython-http-get-requests/

The get request code should look like (and which works without errors)  

```
response = urequests.get('http://jsonplaceholder.typicode.com/albums/1')
print(type(response))
```

UIFlow Generates a GET request as follows 
```
try:
  req = urequests.request(method='GET', url='http://jsonplaceholder.typicode.com/albums/1', headers={})
except:
  pass
```

For some weird reason, this Blockly generated code throws an error always. 

UIFlow 1.4.0 Beta
Firmware: 1.4.0
Device: Basic Development Kit. 

My functional code which generates the below Project
```

from m5stack import *
from m5ui import *
from uiflow import *
import urequests

setScreenColor(0x222222)




label0 = M5TextBox(10, 92, "&", lcd.FONT_DejaVu40,0xFFFFFF, rotate=0)
rectangle0 = M5Rect(0, 0, 317, 60, 0x3215ea, 0x1b2eb7)
label1 = M5TextBox(10, 8, "Bitcoin Price", lcd.FONT_DejaVu40,0xFFFFFF, rotate=0)

buttonA_wasPressed()



def buttonA_wasPressed():
  try:
    req = urequests.get('https://api.thingspeak.com/apps/thinghttp/send_request?api_key=AAXWP1R39OHJW1U1')
    label0.setText(req.text)
  except:
    label0.setText('Error')
  pass
btnA.wasPressed(buttonA_wasPressed)
```

![image](https://user-images.githubusercontent.com/460081/66145546-b4ecaa00-e628-11e9-811d-135beaa9ac27.png)

**Comment by EeeeBin** [comment]
Test it, found work well
![image](https://user-images.githubusercontent.com/24584225/66444750-05279a00-ea77-11e9-8ea7-e5a268f2ecf3.png)
